from percolation_1 import percolation_1
from percolation_2 import percolation_2
from percolation_3 import percolation_3
from percolation_4 import percolation_4
from percolation_5 import percolation_5
from percolation_6 import percolation_6