from infiltration_1 import infiltration_1
from infiltration_2 import infiltration_2
from infiltration_3 import infiltration_3
from infiltration_4 import infiltration_4
from infiltration_5 import infiltration_5
from infiltration_6 import infiltration_6
from infiltration_7 import infiltration_7
from infiltration_8 import infiltration_8